### PR TITLE
Add Barbarian Rage Counters

### PR DESCRIPTION
**Pull request by ktrieun**

### CODE REVIEW

**Comment by kinkofer** [comment]
This looks like a good addition. I’ll need to account for this in the validation first though. I’ll be able to do that tomorrow.

**Comment by dragonahcas** [comment]
This wasn't included before as the ability to add monk ki and barbarian rage was only recently added by the Dev in the last few updates. Previously this had to be done manually.

**Comment by ktrieun** [comment]
I'll add the Monk's Ki Points and Fighter's various non-spellslot resources later when i have the chance. Are there any other classes that have that sort of resource?

**Comment by dragonahcas** [comment]
I think the release notes only mentioned rage and ki. 

Maybe a counter for sorcery points but I don't know the specifics on how they accumulate. 

Lay On Hands by Paladin? 5x the Paladin level.

**Comment by kinkofer** [comment]
@ktrieun, please try merging my master into yours now. It includes validation for the counter.

**Comment by kinkofer** [comment]
@ktrieun I'm not seeing the counter show up when creating a new Barbarian. Is this working for you?

**Comment by ktrieun** [comment]
Yeah, it's not a selectable option. When you finish creating a character, it'll appear in the Statistics area

**Comment by ktrieun** [comment]
As you level up,  auto change the reset value for that tracker

**Comment by kinkofer** [comment]
I see it, thanks :)

**Pull request merged**
