### PR TITLE
Added sorcery points

### PR DESCRIPTION
**Pull request by Bloodis94**

### CODE REVIEW

**Comment by esabol** [comment]
@Bloodis94 : If you change
```
    - rvm install 2.3.8
```
to
```
    - rvm install 2.4.5
```
in the `.travis.yml` file, the checks will start working.

**Comment by Bloodis94** [comment]
Ty, i will push the fix and update the pull
Il 6 giu 2021, 21:53 +0200, Ed Sabol ***@***.***>, ha scritto:

**Review by esabol — APPROVED** [review]

**Comment by esabol** [comment]
This makes me sad.

**Comment by zcdziura** [comment]
> This makes me sad.

Why?

**Comment by Bloodis94** [comment]
> This makes me sad.

I've deleted this repository since I'm moving to the ogre-project fork of this project. This Pr is already merged there.

**Comment by esabol** [comment]
> I've deleted this repository since I'm moving to the ogre-project fork of this project. This Pr is already merged there.

Oh, OK. Thanks! This makes me happy. :rofl:

**Pull request closed without merging**
