### PR TITLE
Get Travis CI working for PRs again

### PR DESCRIPTION
**Pull request by esabol**
This PR updates `.travis.yml` to use newer version of Ruby (2.4.5) in order to get Travis CI working again for PRs. It at least partially addresses issue #161.

### CODE REVIEW

**Comment by esabol** [comment]
The “**Travis CI - Branch** _Expected — Waiting for status to be reported_” should be able to be fixed by following the **Remedy** instructions found here:

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by kinkofer** [comment]
Dropbox shut down our operation, that's why this is no longer working. I've removed Dropbox deployment in #168.

**Comment by esabol** [comment]
I think you still need to do this part to get CI fully working:

The “**Travis CI - Branch** _Expected — Waiting for status to be reported_” message should be fixed by following the **Remedy** instructions found here:

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by kinkofer** [comment]
My settings are already configured that way. I think it has to do with
being a PR from another repo possibly, because for my own PR it reports
correctly.

**Comment by esabol** [comment]
Well, it's working now! The yellow statuses are all now all green.

**Pull request closed without merging**
