### PR TITLE
Added a simple build-script to the root folder.

### PR DESCRIPTION
**Pull request by vidalvanbergen**
Could maybe use an explanation in the readme, but this creates Fight Club importable files in a 'Compendiums' folder.

### CODE REVIEW

**Comment by esabol** [comment]
I think you're missing a newline at the end of line 2 of build-collections.sh? Might want to add that.

**Comment by vidalvanbergen** [comment]
I'm not sure why GitHub asks for a new line at the end of file, but i've added it.

**Comment by esabol** [comment]
> I'm not sure why GitHub asks for a new line at the end of file, but i've added it.

GitHub didn't. I did. As for why, [POSIX says so](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206). Plenty of additional discussion here: 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by vidalvanbergen** [comment]
Ah I see, interesting information. Thanks.

**Comment by zcdziura** [comment]
@kinkofer Will you take a look at this PR and merge if you think that things look OK?

**Review by kinkofer — APPROVED** [review]

**Pull request merged**
